apiVersion: 1

# List of data sources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# List of data sources to insert/update depending on what is available in the database
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    password:
    user:
    database:
    basicAuth: false
    isDefault: true
    jsonData:
      timeInterval: 15s
      alerting:
        noDataAlert: true
        noDataState: alerting
    readOnly: false
    editable: true
