"""
Input and output guardrails for the AI agent.
Input: PII masking, prompt injection blocking, message length enforcement.
Output: Data stripping, disclaimer appending, PII leakage prevention.
"""
import re
from typing import Any


# ============================================================================
# INPUT GUARDRAILS
# ============================================================================


class InputGuard:
    """Sanitize and validate user input before sending to Claude."""

    # Prompt injection patterns (15 common attack vectors)
    INJECTION_PATTERNS = [
        r"ignore previous instructions",
        r"forget the system prompt",
        r"disregard your guidelines",
        r"pretend you are",
        r"role play as",
        r"you are no longer an agent",
        r"admin mode",
        r"bypass security",
        r"execute arbitrary code",
        r"sql injection",
        r"xss payload",
        r"show me the prompt",
        r"what are your instructions",
        r"break character",
        r"jailbreak",
    ]

    # PII patterns (credit cards, phones, emails, govt IDs, etc.)
    PII_PATTERNS = {
        "credit_card": r"\b(?:\d[ -]*?){13,19}\b",
        "ssn": r"\b\d{3}-\d{2}-\d{4}\b",
        "phone": r"\b(?:\+1[-.\s]?)?\(?[0-9]{3}\)?[-.\s]?[0-9]{3}[-.\s]?[0-9]{4}\b",
        "email": r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b",
        "aadhaar": r"\b\d{4}\s?\d{4}\s?\d{4}\b",  # Indian ID
        "pan": r"\b[A-Z]{5}[0-9]{4}[A-Z]\b",  # Indian tax ID
        "passport": r"\b[A-Z]{1,2}\d{6,9}\b",
    }

    MAX_MESSAGE_LENGTH = 10000  # characters

    @classmethod
    def sanitize(cls, user_input: str) -> tuple[str, list[str]]:
        """
        Sanitize user input.
        Returns: (sanitized_text, list_of_redactions)
        """
        sanitized = user_input
        redactions = []

        # 1. Check for prompt injection patterns
        for pattern in cls.INJECTION_PATTERNS:
            if re.search(pattern, sanitized, re.IGNORECASE):
                redactions.append(f"Blocked prompt injection attempt: {pattern}")
                sanitized = re.sub(pattern, "[BLOCKED]", sanitized, flags=re.IGNORECASE)

        # 2. Mask PII
        for pii_type, pattern in cls.PII_PATTERNS.items():
            matches = re.findall(pattern, sanitized)
            if matches:
                redactions.append(f"Masked {pii_type}: {len(matches)} instance(s)")
                if pii_type == "credit_card":
                    sanitized = re.sub(pattern, "[CREDIT_CARD_REDACTED]", sanitized)
                elif pii_type == "email":
                    sanitized = re.sub(pattern, "[EMAIL_REDACTED]", sanitized)
                elif pii_type in ["phone", "ssn"]:
                    sanitized = re.sub(pattern, "[PHONE_REDACTED]", sanitized)
                else:
                    sanitized = re.sub(pattern, f"[{pii_type.upper()}_REDACTED]", sanitized)

        # 3. Check message length
        if len(sanitized) > cls.MAX_MESSAGE_LENGTH:
            redactions.append(f"Message truncated from {len(user_input)} to {cls.MAX_MESSAGE_LENGTH} chars")
            sanitized = sanitized[: cls.MAX_MESSAGE_LENGTH]

        return sanitized, redactions


# ============================================================================
# OUTPUT GUARDRAILS
# ============================================================================


class OutputGuard:
    """Sanitize agent output before sending to user/frontend."""

    # Sensitive data patterns to strip
    SENSITIVE_PATTERNS = {
        "api_key": r"api[_-]?key['\"]?\s*[:=]\s*['\"]?[A-Za-z0-9_\-]{20,}['\"]?",
        "password": r"(?i)password['\"]?\s*[:=]\s*['\"]?[^'\"}\s]{6,}['\"]?",
        "cost": r"(?i)(?:cost|margin|profit)[:=\s]+[\$€£¥]?\d+(?:\.\d{2})?",
        "credit_card": r"\b(?:\d[ -]*?){13,19}\b",
        "jwt": r"eyJ[A-Za-z0-9_-]+\.eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+",
    }

    # Policy disclaimer
    DISCLAIMER = (
        "\n\n---\n"
        "*Note: This response was generated by an AI agent. "
        "All sensitive operations require human review and approval. "
        "For concerns, contact support.*"
    )

    @classmethod
    def sanitize(cls, agent_output: str) -> str:
        """
        Sanitize agent output.
        Strips sensitive data, adds disclaimer.
        """
        sanitized = agent_output

        # Strip sensitive patterns
        for pattern_name, pattern in cls.SENSITIVE_PATTERNS.items():
            if re.search(pattern, sanitized, re.IGNORECASE):
                sanitized = re.sub(pattern, f"[{pattern_name.upper()}_REDACTED]", sanitized, flags=re.IGNORECASE)

        # Check for accidental multi-user data leakage (simple heuristic)
        if "user_id:" in sanitized or "customer_id:" in sanitized:
            # Only expose if it's the queried user, not other customers
            pass  # This would require context; for now, rely on backend ACLs

        # Append disclaimer for agent-generated content
        if not sanitized.endswith(cls.DISCLAIMER):
            sanitized += cls.DISCLAIMER

        return sanitized

    @classmethod
    def strip_internal_cost_data(cls, data: dict[str, Any]) -> dict[str, Any]:
        """Remove cost/margin data from dicts before returning to customer."""
        if isinstance(data, dict):
            return {
                k: v
                for k, v in data.items()
                if k.lower() not in ["cost_price", "margin", "profit", "wholesale_price", "internal_cost"]
            }
        return data


def apply_input_guardrails(user_message: str) -> tuple[str, list[str]]:
    """Apply all input guardrails and return sanitized message + warnings."""
    return InputGuard.sanitize(user_message)


def apply_output_guardrails(agent_response: str) -> str:
    """Apply all output guardrails to agent response."""
    return OutputGuard.sanitize(agent_response)
